# Generated by Django 4.2.1 on 2023-05-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Долгота'),
        ),
    ]
