# Generated by Django 4.2.1 on 2023-05-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
    ]
