name: Main_places_remember

on:
  push:
    branches:
      - main  # Здесь укажите ветку, на которой будет запускаться GitHub Actions
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest  # Здесь можно выбрать другой образ, если нужно

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7  # Здесь укажите версию Python, используемую в вашем проекте

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Django==3.2.19
          pip install django-allauth==0.54.0
          pip install folium==0.14.0
          pip install geocoder==1.38.1
          pip install django-crispy-forms==2.0
          pip install flake8==5.0.4
          pip install flake8-broken-line==0.6.0
          pip install flake8-isort==6.0.0
          pip install flake8-plugin-utils==1.3.2
          pip install flake8-return==1.2.0
          pip install coverage==7.2.5

      - name: Run tests and coverage
        run: |
          cd project/
          python manage.py test
          # coverage run --source='memories' manage.py test -v 2
          coverage run --rcfile=.coveragerc manage.py test

      - name: Upload coverage report to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          pip install coveralls
          coveralls
